### ISSUE TITLE
Issues and feature improvements

### ISSUE THREAD

**Issue by wpsumo** [dbjpanda/kb-elementor#1]
**Issues:**
Found an issue and it does not work for me neither when creating with an elementor heading widget. But would like support for h1-h6 HTML tags and listen to the HTML code and not specific div classes? ut never the less none of the two worked for me. The specific headlines do not have any classes. Clean HTML code, or do you refer to the div tags wrapping the content block.

**Using plugin:**
Elementor
Elementor PRO
ACF PRO

**Content:**
Repeater fields
Theme builder single page template (single.php)

**Improvements:**
- Add support for carousel TOC, align horizontally. Which would create possibilities to add it in a sticky section and better UX/UI for the mobile user.

**Comment by dbjpanda** [comment]
Can you copy paste your html here or a screenshot.  You don't have to choose every classes separately. You have to choose the only parent selector. For example if you want to to grab all headings from entire page you have to input 'body' in the additional option. 
For the feature request to add horizontal alignment I have created another issue here. #2 Please provide your input there if you find any examples what you want to do.

**Comment by wpsumo** [comment]
@dbjpanda body works did not fully understand that additional tab. But for some reason 2 last links in the toc does not link. On the test page, there are 15 headlines. In the HTML code seems alright but not possible to click and jump without opening the dev tools and click on the specific # jump link in the `a href`. 

Also facing issues with the icons to open the TOC. When adding icons to both it closes but then no icon to open.

Would also be nice to be able to align the specific widget to left center right.

Preferably reset the link color to default which listens to global style and option to assign `:hover` color as well.

Also thinks there should be a possibility to disable and style the color of the underline on the headline it jumps to?

**Comment by dbjpanda** [comment]
Screenshot or a screencast please. Without some resources I can't help much. All the settings and configuration hasn't been documented yet. So you might be facing issue. Please atleast copy paste your html source code.

**Comment by wpsumo** [comment]
@dbjpanda prefer to keep it private. 

But some issues and improvement are added above. Edited my comment a few times so might be things you missed.

Another thing see that the notation style is not 100% or not what I want maybe.

```
1.
1.1
1.2
1.3
2.
2.1
3.
3.1
4.
4.1
4.2
4.3
4.4
etc..
```

**Comment by wpsumo** [comment]
Heading Offset is the one messing with the last jump links. Removed and kept it blank and it is working. But then we have another issue that it doesn't jump to the exact headline location.

So right now if I use offset It jump correctly. But the more I increase it the fewer jump links works from the bottom upwards. So there is some bug there. Or keep offset blank and it does not jump to the right headline location.

**Comment by dbjpanda** [comment]
> So right now if I use offset It jump correctly. But the more I increase it the fewer jump links works from the bottom upwards. So there is some bug there. Or keep offset blank and it does not jump to the right headline location. 

I understand it. That is a good test case to experiment. The main problem is I have tried to make the plugin more css dependent instead of Jquery for better performance. So some CSS tinkering can fix issue of scrolling. 

Can you please create separate issues for separate problems. In one issue everything can't be tracked easily. I have considered some of your requests as feature enhancement. Subscribe those issues or star the repo to get updates. I will be eventually fixing those and make it stable.

**Comment by dbjpanda** [comment]
@alriksson If you can show me your html or give me access to your development site, I can easily find out the issue. You can contact me via https://dbjpanda.me/contact

**Comment by wpsumo** [comment]
>@alriksson If you can show me your html or give me access to your development site, I can easily find out the issue. You can contact me via https://dbjpanda.me/contact

I will see if I have time this week to setup the staging for external access.
You don't face these issues?

>I understand it. That is a good test case to experiment. The main problem is I have tried to make the plugin more css dependent instead of Jquery for better performance. So some CSS tinkering can fix issue of scrolling.

That is great, less jquery, please. Less code in general thanks, if elementor ever would prioritize that in an extreme manner! So many widget and code loaded that isn't used. Many good solutions to it. to compile upon save and unlock all code when building only and then generate the files for frontend based on what is used. Anyhow off topic here but I'm happy you prioritize performance.

>Can you please create separate issues for separate problems. In one issue everything can't be tracked easily. I have considered some of your requests as feature enhancement. Subscribe those issues or star the repo to get updates. I will be eventually fixing those and make it stable

Noted!

**Comment by dbjpanda** [comment]
@alriksson Yes in my case it is working perfectly except one issue show/ hide button #8 which I have fixed and pushed. You can try now updating your plugin https://wordpress.org/plugins/kb-elementor . Here is my demo site https://dbjpanda.me/database/dbms/database-models where it works.

**Comment by dbjpanda** [comment]
Closing it as the corresponding requests have been created in new issues. Please follow those issues to get updates.
