### ISSUE TITLE
Plugin causes empty taxonomy list on edit-tags.php

### ISSUE THREAD

**Issue by sambbaron** [dbjpanda/kb-elementor#14]
I just started using this plugin, and I've found an unusual bug. When the plugin is activated, the taxonomy list on edit-tags.php is empty. The screenshot below is for categories. If I deactivate the plugin and refresh this screen, my categories are listed. Same effect with custom taxonomies.

Maybe a conflict with another plugin? I deactivated a few potential options, but it didn't fix the problem (Advanced Custom Fields, Custom Post Type UI, RankMath-SEO plugin). I'm using the latest versions of Elementor and Elementor Pro.

![kb-elementor](https://user-images.githubusercontent.com/10456742/62311556-e71f3700-b440-11e9-9d63-9b9177a62de0.PNG)

**Comment by dbjpanda** [comment]
Thanks for reporting the issue. I will try to help you out. I tried some test on my site, but everything works well as you can see the screenshot.
![Screen Shot 2019-08-02 at 8 05 13 AM](https://user-images.githubusercontent.com/17483092/62340241-848b7100-b4fc-11e9-95a6-1c3974b72b34.png)

Can you give me some more details if you are seeing any error in browser console. While on `edit-tags.php` page `Right click > Inspect` then go to `console` tab there.

**Comment by sambbaron** [comment]
I am not seeing any errors in the browser console.

**Comment by dbjpanda** [comment]
Then, try installing it on a fresh wordpress installation. Otherwise let me give access to your site to investigate the issue (But I will do that while get some free time). So better try on a fresh installation.

**Comment by sambbaron** [comment]
Okay, I just created a fresh installation, the only plugins are Elementor and KB-Elementor. I created two categories and two tags, no other data or modifications, and the problem is still happening. I'll email you with the website access info.

**Comment by dbjpanda** [comment]
Hi, the issue has been fixed and pushed to both Github and Wordpress. Download the version 1.0.4 from here ( https://github.com/dbjpanda/kb-elementor/releases ). Or update the plugin in your wordpress dashboard(It may take some time to get an update notification). 

Thanks for reporting the issue.

Consider giving your rating for the plugin here https://wordpress.org/support/plugin/kb-elementor/reviews/#new-post . It motivates the developer who works in free of cost.

**Comment by sambbaron** [comment]
👍👍
