### ISSUE TITLE
Plugin removed from WordPress.org

### ISSUE THREAD

**Issue by MiMoHo** [dbjpanda/kb-elementor#22]
Your plugin was removed from the [WordPress.org site](https://en-gb.wordpress.org/plugins/kb-elementor/) on August 8. What was the issue and will you relist it?

**Comment by dbjpanda** [comment]
Hi @MiMoHo Extremely sorry for the inconvenience. 

> As of 8th Aug 2019, we refactored this "table of contents for Elementor" plugin from KB Elementor to [TOC Pack](https://dbjpanda.me/apps/tocpack). Afterwards it will be available as a premium plugin with premium supports. You can download TOC pack from [here](https://dbjpanda.me/apps/tocpack) donating very small amount of money.

Thanks for showing your interest in the plugin. Hope we will be connected soon with premium supports.
